# To run with main.py

# NAME XP
folder: "conference"
name_xp: "low_battery_wear" # limit_15, battery_factor_0_25, california

# EXPERIMENT TYPE
experiment_types: ["coordinated", "uncoordinated"]
  # "uncoordinated" or "coordinated" or "inelastic_coordinated" or "unidirectional_coordinated" or "centralized"


# NUMBER OF RUNS
num_runs: 1

# ADMM PARAMETERS
nu: 0.1
nu_multiplier: 1.1
max_iter: 100

# SIMULATION PARAMETERS
stochastic: false
time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
market_prices: [40.12, 42.28, 43.46, 46.59, 60.65, 65.67, 70.41, 85.57, 142.20, 248.21, 116.28, 82.23] # July 12, in $/MWh, 10 AM to 10 PM, California
granularity: 4
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 15
alpha_factor: 1.0
battery_factor: 0.25
alpha_model_path: "models/gmm_alpha.pkl"
disconnection_model_path: "models/gmm_disconnection_model.pkl"
soc_model_path: "models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf 0.13
    disconnection_time_flexibility: 62 # ~30$ for delaying by 1h
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 18
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 15 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 30
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 19
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6
    min_soc: 15
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 52
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 20 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 
    min_soc: 15
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 19 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 
    min_soc: 15 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 29
    soc_flexibility: 10
    energy_efficiency: 0.87

vcg: true

plots:
  - soc_evolution
  - market_prices
  - ev_total_cost_comparison
  - vcg_vs_disconnection_time
