# Run with main_bid_value.py


# NAME XP
folder: "final/bid_value"
name_xp: "bid_chart"

# EXPERIMENT TYPE
experiment_types: ["coordinated"]
  # "uncoordinated" or "coordinated" or "inelastic_coordinated" or "unidirectional_coordinated" or "centralized"

# NUMBER OF RUNS
num_runs: 20

# ADMM PARAMETERS
nu: 0.1
nu_multiplier: 1.1
max_iter: 100

# SIMULATION PARAMETERS
stochastic: true
alpha_deterministic: true # if true, alpha is deterministic even stochastic is true
time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
market_prices: [141.93,134.66,131.39,132.57,138.1,151.38,144.9,223.78,198.09,171.76,168.51,156.74] # Jan. 16, in $/MWh, 7 AM to 12 AM
# market_prices: [40.12, 42.28, 43.46, 46.59, 60.65, 65.67, 70.41, 85.57, 142.20, 248.21, 116.28, 82.23] # July 12, in $/MWh, 10 AM to 10 PM, California
granularity: 4
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 30 # so oversubscription of 3.3 
alpha_factor: 1.0
battery_factor: 1.0
alpha_model_path: "models/gmm_alpha.pkl"
disconnection_model_path: "models/gmm_disconnection_model.pkl"
soc_model_path: "models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf 0.13
    disconnection_time_flexibility: 64 # 5c for delaying by 1h
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 56
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 21 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 58
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 5
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf 0.13
    disconnection_time_flexibility: 62 # 5c for delaying by 1h
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 6
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 7
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 57
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 8
    disconnection_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 9
    disconnection_time: 21 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 10
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf 0.13
    disconnection_time_flexibility: 62 # 5c for delaying by 1h
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 11
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 12
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 13
    disconnection_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 58
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 14
    disconnection_time: 21 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6 # Nissan leaf limit
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 50
    soc_flexibility: 10
    energy_efficiency: 0.87

# METRICS/RESULTS
# walras_tax: true
# vcg: true

plots:
  #- total_cost_vs_energy_cost
  - soc_evolution
  - market_prices
  # - total_cost_bars
  # - payment_comparison
  # - total_cost_benchmarking
  - v2g_fraction
