# NAME XP
folder: "final/strategic"
name_xp: "strategic"

# EXPERIMENT TYPE
experiment_types: ["coordinated"]  
    # "uncoordinated" or "coordinated" or "inelastic_coordinated" or "unidirectional_coordinated" or "centralized"

# NUMBER OF RUNS
num_runs: 1

# ADMM PARAMETERS
nu: 0.1
nu_multiplier: 1.1
max_iter: 20

# SIMULATION PARAMETERS
stochastic: false
time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
market_prices: [141.93,134.66,131.39,132.57,138.1,151.38,144.9,223.78,198.09,171.76,168.51,156.74] # Jan. 16, in $/MWh
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 25
granularity: 4
alpha_factor: 1
price_factor: 1
alpha_model_path: "models/gmm_alpha.pkl"
disconnection_model_path: "models/gmm_disconnection_model.pkl"
soc_model_path: "models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01 # for Nissan Leaf 0.13
    disconnection_time_flexibility: 0.1 # 5c for delaying by 1h
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_flexibility: 0.12
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_flexibility: 0.1
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_flexibility: 0.08
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_flexibility: 0.1
    soc_flexibility: 10
    energy_efficiency: 0.87

# METRICS/RESULTS
walras_tax: true
vcg: false
nash_check: true
ev_nash: 2
tau_nash: [16, 17, 18, 19, 20]
alpha_nash: [0.06, 0.08, 0.10, 0.12, 0.14]

plots:
  # - total_cost_vs_energy_cost
  - soc_evolution
  - market_prices
  #- total_cost_bars
  # - payment_comparison
  # - total_cost_benchmarking
  # - v2g_fraction
  # - evcs_power
