# NAME XP
folder: "tests"
name_xp: "vcg_simple_test"

# EXPERIMENT TYPE
experiment_types: ["coordinated"]  
    # "uncoordinated" or "coordinated" or "inelastic_coordinated" or "unidirectional_coordinated"

# NUMBER OF RUNS
num_runs: 1

# SIMULATION PARAMETERS
stochastic: false
time_range: [10, 12]  # Time from 10 AM to 12 PM
seed: 42
market_prices: [1, 3]
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 10
alpha_factor: 1
price_factor: 1
alpha_model_path: "models/gmm_alpha.pkl"
disconnection_model_path: "models/gmm_disconnection_model.pkl"
soc_model_path: "models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 12 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 10
    soc_threshold: 0
    initial_soc: 0
    desired_soc: 10
    max_charge_rate: 10
    max_discharge_rate: 10
    min_soc: 0
    battery_wear_cost_coefficient: 0
    disconnection_time_preference_coefficient: 2000  # high cost to avoid change in disconnection time
    energy_efficiency: 1
  - id: 1
    disconnection_time: 12 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 10
    soc_threshold: 0
    initial_soc: 0
    desired_soc: 10
    max_charge_rate: 10
    max_discharge_rate: 10
    min_soc: 0
    battery_wear_cost_coefficient: 0
    disconnection_time_preference_coefficient: 2000  # high cost to avoid change in disconnection time
    energy_efficiency: 1

# METRICS/RESULTS
walras_tax: true
vcg: true

plots:
    -
