# NAME XP
folder: "nash"
name_xp: "equilibrium_ev0_check"

# EXPERIMENT TYPE
experiment_types: ["coordinated"]  
    # "uncoordinated" or "coordinated" or "inelastic_coordinated" or "unidirectional_coordinated" or "centralized"

# NUMBER OF RUNS
num_runs: 1

# SIMULATION PARAMETERS
stochastic: false
time_range: [7, 24]  # Time from 7 AM to 12 AM
seed: 42
market_prices: [215.06,162.85,151.21,141.93,134.66,131.39,132.57,138.1,151.38,144.9,223.78,198.09,171.76,168.51,156.74,143.17,146.16] # Jan. 16, in #/MWh
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 25
alpha_factor: 1
price_factor: 1
alpha_model_path: "models/gmm_alpha.pkl"
disconnection_model_path: "models/gmm_disconnection_model.pkl"
soc_model_path: "models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01 # for Nissan Leaf 0.13
    disconnection_time_preference_coefficient: 0.1 # 5c for delaying by 1h
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_preference_coefficient: 0.12
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_preference_coefficient: 0.1
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_preference_coefficient: 0.08
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 12
    desired_soc: 40
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.01
    disconnection_time_preference_coefficient: 0.1
    energy_efficiency: 0.87

# METRICS/RESULTS
walras_tax: true
vcg: false
nash_check: true
ev_nash: 0
tau_nash: [16, 17, 18, 19, 20, 21, 22]
alpha_nash: [0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13]

plots:
  - total_cost_vs_energy_cost
  - soc_evolution
  - market_prices
  - total_cost_bars
  - payment_comparison
  # - total_cost_benchmarking
  # - v2g_fraction
  # - evcs_power
