# NAME XP
name_xp: "test_coupled_xp"

# EXPERIMENT TYPE
experiment_types: ["coupled_centralized_scheduling"]  
    # "uncoordinated" or "centralized_scheduling" or "inelastic_centralized_scheduling" or "coupled_centralized_scheduling"

# NUMBER OF RUNS
num_runs: 1

# SIMULATION PARAMETERS
stochastic: true
time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
market_prices: [37.03, 35.75, 42.48, 42.81, 43.1, 43.12, 42.71, 43.16, 53.1, 46.22, 44.31, 43.25]
market_prices_csv: "C:/Users/sabri/Projects/v2g_mechanism_project/data/processed/day_ahead_prices/hub_prices.csv"
evcs_power_limit: 25

evs:
  - id: 0
    disconnect_time: 14 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf
    disconnection_time_preference_coefficient: 2
    energy_efficiency: 0.87
  - id: 1
    disconnect_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.13
    disconnection_time_preference_coefficient: 2
    energy_efficiency: 0.87
  - id: 2
    disconnect_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.13
    disconnection_time_preference_coefficient: 2
    energy_efficiency: 0.87
  - id: 3
    disconnect_time: 18 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.13
    disconnection_time_preference_coefficient: 2
    energy_efficiency: 0.87
  - id: 4
    disconnect_time: 20 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    soc_threshold: 12 # 30 % of the battery capacity
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 11.5 # Wallbox Quasar 2
    max_discharge_rate: 7 # Nissan leaf limit
    min_soc: 0
    battery_wear_cost_coefficient: 0.13
    disconnection_time_preference_coefficient: 2
    energy_efficiency: 0.87

# METRICS/RESULTS
plots:
  - objective_vs_cost
  - soc_evolution
  - market_prices
  - objective_bars
