# NAME XP
folder: "tsg/xp_5/vcg_time_16_af_0.25_20250814_090113"
name_xp: "vcg"

# EXPERIMENT TYPE
experiment_types: ["centralized"]

# NUMBER OF RUNS
num_runs: 20

# ADMM PARAMETERS
nu: 0.1
nu_multiplier: 1.1
max_iter: 100

# SIMULATION PARAMETERS
extreme_days: true
stochastic: true
override: true
override_disconnection_time: 16

time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
granularity: 4
market_prices_csv: "../data/hub_prices.csv"
evcs_power_limit: 10 # so oversubscription of 3.3 
alpha_factor: 0.25
battery_factor: 1.0 

alpha_model_path: "../models/gmm_alpha.pkl"
disconnection_model_path: "../models/gmm_disconnection_model.pkl"
soc_model_path: "../models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 19 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 # Caltech parking lot
    max_discharge_rate: 6.6
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf
    disconnection_time_flexibility: 62 
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 18 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 15 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 19
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 15 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 20
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6
    min_soc: 15 # equal to initial_soc
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 58
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 21 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 15 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 50
    soc_flexibility: 10
    energy_efficiency: 0.87

# METRICS/RESULTS
vcg: true

plots:
  - soc_evolution
