# NAME XP
folder: "tsg/xp_3"
name_xp: "congestion_soc"

# EXPERIMENT TYPE
experiment_types: ["centralized"]

# NUMBER OF RUNS
num_runs: 1

# ADMM PARAMETERS
nu: 0.1
nu_multiplier: 1.1
max_iter: 100

# SIMULATION PARAMETERS
stochastic: false
time_range: [10, 22]  # Time from 10 AM to 10 PM
seed: 42
market_prices: [141.93,134.66,131.39,132.57,138.1,151.38,144.9,223.78,198.09,171.76,168.51,156.74] # Jan. 17, in $/MWh, 10 AM to 10 PM
granularity: 4
market_prices_csv: "../data/hub_prices.csv"
evcs_power_limit: 10
alpha_factor: 1.0
battery_factor: 1.0 
alpha_model_path: "../models/gmm_alpha.pkl"
disconnection_model_path: "../models/gmm_disconnection_model.pkl"
soc_model_path: "../models/initial_final_soc_kde.pkl"

evs:
  - id: 0
    disconnection_time: 17 # should be between time_range[0]+1 and time_range[1] (included)
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 # Caltech parking lot
    max_discharge_rate: 6.6
    min_soc: 0
    battery_wear_cost_coefficient: 0.13 # for Nissan Leaf
    disconnection_time_flexibility: 62 
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 1
    disconnection_time: 18 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 0 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 60
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 2
    disconnection_time: 19
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 0 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 54
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 3
    disconnection_time: 20
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6 
    max_discharge_rate: 6.6
    min_soc: 0
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 58
    soc_flexibility: 10
    energy_efficiency: 0.87
  - id: 4
    disconnection_time: 19 
    battery_capacity: 40
    initial_soc: 15
    desired_soc: 35
    max_charge_rate: 6.6
    max_discharge_rate: 6.6
    min_soc: 0 
    battery_wear_cost_coefficient: 0.13
    disconnection_time_flexibility: 50
    soc_flexibility: 10
    energy_efficiency: 0.87

# METRICS/RESULTS
plots:
  - soc_evolution
